name: Manual Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      pr_title:
        description: 'Pull Request Title'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment based on PR title
        run: |
          if [[ "${{ github.event.inputs.pr_title }}" == *"ap"* ]]; then
            echo "Running AP region deployment"
            echo "REGION=ap" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.pr_title }}" == *"eu"* ]]; then
            echo "Running EU region deployment"
            echo "REGION=eu" >> $GITHUB_ENV
          else
            echo "Running default region deployment"
            echo "REGION=default" >> $GITHUB_ENV
          fi
          
      - name: Deploy to environment
        run: |
          if [ "$REGION" == "ap" ]; then
            echo "Deploying to AP region"
            # Add your AP deployment commands here
          elif [ "$REGION" == "eu" ]; then
            echo "Deploying to EU region"
            # Add your EU deployment commands here
          else
            echo "Deploying to default region"
            # Add your default deployment commands here
          fi
